param([Parameter(Mandatory=$true)][ValidateSet('java-classic','interop')][string]$Mode)
$ErrorActionPreference='Stop'
Set-Location -LiteralPath $PSScriptRoot
function Is-Admin { $id=[Security.Principal.WindowsIdentity]::GetCurrent(); $p=New-Object Security.Principal.WindowsPrincipal($id); return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator) }
function Hash-Path([string]$p) { $n=[IO.Path]::GetFullPath($p).TrimEnd('\').ToLowerInvariant(); $sha=[Security.Cryptography.SHA256]::Create(); try{$h=$sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($n))}finally{$sha.Dispose()}; return (($h|ForEach-Object{$_.ToString('x2')}) -join '') }
function Has-Ascii([string]$Path,[string]$Text) { if(-not(Test-Path -LiteralPath $Path)){return $false}; $d=[IO.File]::ReadAllBytes($Path); $n=[Text.Encoding]::ASCII.GetBytes($Text); for($i=0;$i -le $d.Length-$n.Length;$i++){ $ok=$true; for($j=0;$j -lt $n.Length;$j++){if($d[$i+$j] -ne $n[$j]){$ok=$false;break}}; if($ok){return $true} }; return $false }
if(-not [Environment]::Is64BitOperatingSystem){throw 'Requires Windows 8.1 x64.'}
if(-not [Environment]::Is64BitProcess){throw 'Run with 64-bit PowerShell.'}
$os=(Get-WmiObject Win32_OperatingSystem).Version; if(-not $os.StartsWith('6.3.')){throw ('Only Windows 8.1 (6.3) is supported. Detected: '+$os)}
if(-not(Is-Admin)){ $arg='-NoProfile -ExecutionPolicy Bypass -File "'+$PSCommandPath+'" -Mode '+$Mode; $p=Start-Process "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -Verb RunAs -ArgumentList $arg -Wait -PassThru; exit $p.ExitCode }
$game=Join-Path $PSScriptRoot 'Minecraft.Windows.exe'; if(-not(Test-Path -LiteralPath $game)){throw 'Put this coexistence test package beside the target Minecraft.Windows.exe.'}; $game=[IO.Path]::GetFullPath($game)
if($Mode -eq 'interop') { $pix=Join-Path $PSScriptRoot 'WinPixEventRuntime.dll'; if(Test-Path -LiteralPath $pix){ if((Has-Ascii $pix 'SetThreadDescription') -and -not(Has-Ascii $pix 'W81KERN.dll')){ throw 'Interop WinPix is not prepared yet. First use the verified Interop v2.0.1 bridge once so WinPix/W81KERN compatibility is installed, then run this registration again.' }; if(Has-Ascii $pix 'W81KERN.dll'){ $shim=Join-Path $PSScriptRoot 'W81KERN.dll'; if(-not(Test-Path -LiteralPath $shim)){throw 'WinPix is redirected to W81KERN.dll, but W81KERN.dll is missing in this game directory.'} } } }
$shared=Join-Path $env:ProgramData 'MCBedrock-LegacyWindows\Win81UniversalBridge'; New-Item -ItemType Directory -Path $shared -Force|Out-Null
$src=Join-Path $PSScriptRoot 'shared\Win81UniversalBridge.cs'; if(-not(Test-Path -LiteralPath $src)){throw 'shared\Win81UniversalBridge.cs is missing.'}; Copy-Item -LiteralPath $src -Destination (Join-Path $shared 'Win81UniversalBridge.cs') -Force
$exe=Join-Path $shared 'Win81UniversalBridge.exe'; if(Test-Path -LiteralPath $exe){Remove-Item -LiteralPath $exe -Force}
$provider=New-Object Microsoft.CSharp.CSharpCodeProvider; $cp=New-Object System.CodeDom.Compiler.CompilerParameters; $cp.GenerateExecutable=$true; $cp.GenerateInMemory=$false; $cp.OutputAssembly=$exe; $cp.CompilerOptions='/platform:x64 /optimize+ /target:exe'; [void]$cp.ReferencedAssemblies.Add('System.dll'); $source=[IO.File]::ReadAllText((Join-Path $shared 'Win81UniversalBridge.cs'),[Text.Encoding]::UTF8); $r=$provider.CompileAssemblyFromSource($cp,@($source)); if($r.Errors.Count -gt 0){foreach($e in $r.Errors){Write-Host ('[CS] '+$e)};throw 'Universal Bridge compilation failed.'}
$ifeo='HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Minecraft.Windows.exe'; $wanted='"'+$exe+'"'; $existing=$null; try{$existing=(Get-ItemProperty -LiteralPath $ifeo -Name Debugger -ErrorAction Stop).Debugger}catch{}
if($existing -and $existing -ne $wanted){ $leaf=[IO.Path]::GetFileName($existing.Trim('"')); if($leaf -ne 'Win81JavaClassicBridge.exe' -and $leaf -ne 'Win81MinecraftBridge.exe'){throw ('Another tool owns the Minecraft.Windows.exe IFEO Debugger: '+$existing)}; Write-Host ('[MIGRATE] Replacing known legacy project bridge: '+$existing) }
if(-not(Test-Path -LiteralPath $ifeo)){New-Item -Path $ifeo -Force|Out-Null}; New-ItemProperty -LiteralPath $ifeo -Name Debugger -PropertyType String -Value $wanted -Force|Out-Null
$hash=Hash-Path $game; $tk='HKLM:\SOFTWARE\MCBedrock-LegacyWindows\Win81UniversalBridge\Targets\'+$hash; New-Item -Path $tk -Force|Out-Null; New-ItemProperty -LiteralPath $tk -Name Path -PropertyType String -Value $game -Force|Out-Null; New-ItemProperty -LiteralPath $tk -Name Mode -PropertyType String -Value $Mode -Force|Out-Null; New-ItemProperty -LiteralPath $tk -Name RegisteredBy -PropertyType String -Value 'coexistence-test-v0.1' -Force|Out-Null
Write-Host '[OK] Universal Bridge installed/updated.'; Write-Host ('[OK] Registered target: '+$game); Write-Host ('[OK] Mode: '+$Mode); Write-Host '[INFO] Other registered Minecraft.Windows.exe paths are preserved.'
